version: "3.6"

services:
  database:
    image: "websublime/postgres"
    container_name: "database"
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ${DATA_PATH}/database:/var/lib/postgresql/data
      - ${PWD}/database:/docker-entrypoint-initdb.d/
